
services:
  consul:
    image: consul:1.15
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
      - "8600:8600/tcp"
    volumes:
      - ./data:/consul/data     
      - ./config:/consul/config  
    command: "agent -server -bootstrap-expect=1 -data-dir=/consul/data -config-dir=/consul/config"

    networks:
      - store_front_network


networks:
  store_front_network:
    external: true
